name: Building Uploader Helper
on: [push]
env:
  ZIG_VERSION: 0.12.0-dev.3290+b9cca3b63
jobs:
  lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: korandoru/setup-zig@v1.6.1
        with:
          zig-version: ${{ env.ZIG_VERSION }}
      - run: zig fmt --check .
  build-release:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Zig
        uses: korandoru/setup-zig@v1.6.1
        with:
          zig-version: ${{ env.ZIG_VERSION }}
      - name: Show Zig version
        run: zig version
      - name: Build executable
        run: zig build -Dversion="${{ github.ref_name }}"
        env:
          GITHUB_REF: ${{ github.ref }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: uploader-helper
          path: zig-out/bin/helper.exe
      - name: Release
        uses: softprops/action-gh-release@v2.0.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: zig-out/bin/helper.exe
           