name: Building Verio Helper
on: [push]
jobs:
  lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig fmt --check .
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
      - name: Build executable
        run: zig build-exe helper.zig
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: verio-helper
          path: helper.exe

            